workdir: /mnt/d/datap/final_assignment/

data-dir: data/
genome: data/genome/Arabidopsis_thaliana.fa
trimmed-dir: data/trimmed/
alignment-dir: data/alignment/
samtools-dir: data/samtools/
snp-dir: data/snp/
samples-dir: data/samples/

result-dir: results/

samples:
  - "single_long"
  - "single_short"
  - "paired_long"
  - "paired_short"

types:
  - "mut"
  - "wt"

threads: 8
threshold_reads: 90.00