workdir: /mnt/d/datap/final_assignment/
genome: data/genome/Arabidopsis_thaliana.fa
trimmed-dir: data/trimmed/
extensions:
  - "pac"
  - "amb"
  - "ann"
  - "sa"
  - "bwt"
samples:
  - "single_long"
  - "single_short"
  - "paired_long"
  - "paired_short"
types:
  - "mut"
  - "wt"
threads: 8
threshold_reads: 90.00