# -*- python -*-
configfile: "config/config.yaml"
workdir: config['workdir']

#include: "workflow/convert.smk"
include: "workflow/filteration.smk"
include: "workflow/alignment.smk"
include: "workflow/samtools.smk"
include: "workflow/snps.smk"
include: "workflow/visualization.smk"

def get_files(wildcards, base_dir):
    if wildcards.sample.startswith('single'):
        return f'{base_dir}{wildcards.sample}_1_{wildcards.type}.fq'
    else:
        return [f'{base_dir}{wildcards.sample}_1_{wildcards.type}.fq', f'{base_dir}{wildcards.sample}_2_{wildcards.type}.fq']

rule all:
    input:
        expand("data/trimmed/{sample}_{index}_{type}_val_{index}.fq", sample=config['samples'], type=config['types'], index=(1,2))