# -*- python -*-
configfile: "config/config.yaml"
workdir: config['workdir']

include: "workflow/convert.smk"
#include: "workflow/filteration.smk"
#include: "workflow/alignment.smk"
#include: "workflow/samtools.smk"
#include: "workflow/snps.smk"
#include: "workflow/visualization.smk"

rule all:
    input:
        fq1 = "data/fq/test_a.fastq",
        fq2 = optional("data/fq/test_b.fastq")